[package]
name = "nordvpn-for-linux"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
gtk = { version = "0.3", package = "gtk4" }
relm4 = { git = "https://github.com/AaronErhardt/relm4/", ref = "v0.4.0-beta.3" }
relm4-macros = { git = "https://github.com/AaronErhardt/relm4/", ref = "v0.4.0-beta.3" }
relm4-components = { git = "https://github.com/AaronErhardt/relm4/", ref = "v0.4.0-beta.3" }
